service: scultureai

package:
  individually: true

provider:
  name: aws
  runtime: python3.8
  region: eu-north-1
  stage: ${opt:stage, "dev"}

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    usePoetry: true
    layer:
      name: scultureai-layer
      description: Assignmentsls
      compatibleRuntimes:
        - python3.8

functions:
  scultureai:
    package:
      include:
        - "main.py"
      exclude:
        - "requirements.txt"
        - "package.json"
        - "package-lock.json"
        - ".serverless/**"
        - ".virtualenv/**"
        - "node_modules/**"

    handler: scultureai.main.handler
    environment:
      STAGE: ${self:provider.stage}
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          method: any
          path: /{proxy+}